migrate to gitlab

diff --git a/rootfs/etc/cont-init.d/30-iptables.init b/rootfs/etc/cont-init.d/30-iptables.init
--- a/rootfs/etc/cont-init.d/30-iptables.init
+++ b/rootfs/etc/cont-init.d/30-iptables.init
@@ -7,40 +7,22 @@ DECTECTED_DOCKER_CIDR=$(ip -o -f inet addr show | awk '/scope global/ {print $4}
 # fallback to DOCKER_CIDR if no DECTECTED_DOCKER_CIDR
 DOCKER_CIDR="${DECTECTED_DOCKER_CIDR:-DOCKER_CIDR}"
 
-# extract VPN protocol, host and port from configuration
-CONFIG_PROTO=$(awk '/proto / { print $2 }' "${OPENVPN_CONFIG_FILE}")
-CONFIG_VPN_HOSTS_AND_PORTS="$(awk '/remote / { print $2 " " $3 }' "${OPENVPN_CONFIG_FILE}")"
-
-VPN_PROTO="${CONFIG_PROTO:='udp'}"
-VPN_HOSTS_AND_PORTS="${CONFIG_VPN_HOSTS_AND_PORTS}"
-
-DNS_SERVER=${DNS}
-
-# Check that VPN information was sucessfully extracted from configuration
-
-if [ -z "${VPN_HOSTS_AND_PORTS}" ]; then
-    echo "ERROR could not find VPN_HOSTS_AND_PORTS in the VPN configuration"
+if [ ! -z "${VPNCONFIG}" ]; then
+    if [ -f /etc/openvpn/"${VPNCONFIG}".ovpn ]; then
+        OPENVPN_CONFIG=/etc/openvpn/${VPNCONFIG}.ovpn
+        echo "Starting OpenVPN using config ${OPENVPN_CONFIG}"
+    else
+        echo "Supplied config ${OPENVPN_CONFIG} could not be found."
+        exit 1
+    fi
+else
+    echo "No VPN configuration provided."
     exit 1
 fi
 
-if [ -z "${VPN_PROTO}" ]; then
-    echo "INFO: the VPN protocol could not be detected, fell back to default:
-    VPN_PROTO:  $VPN_PROTO
-    VPN_HOSTS_AND_PORTS:
-    $VPN_HOSTS_AND_PORTS
-    "
-fi
-
-# change openvpn config 'tcp-client' to compatible iptables 'tcp'
-if [ "${VPN_PROTO}" = "tcp-client" ]; then
-    export VPN_PROTO="tcp"
-fi
-
-# reset iptables
-iptables --flush
-iptables --delete-chain
-iptables -t nat --flush
-iptables -t nat --delete-chain
+export OPENVPN_SERVER_IP=$(awk '/remote / { split($0,a," "); print a[2] }' $OPENVPN_CONFIG)
+export OPENVPN_SERVER_PORT=$(awk '/remote / { split($0,a," "); print a[3] }' $OPENVPN_CONFIG)
+export OPENVPN_SERVER_PROTO=$(awk '/proto/ { split($0,a," "); print a[2] }' $OPENVPN_CONFIG)
 
 # Set default policies to drop all communication unless specifically allowed
 iptables -P INPUT DROP
@@ -52,29 +34,20 @@ iptables -A INPUT -j ACCEPT -i lo
 iptables -A OUTPUT -j ACCEPT -o lo
 
 # allow DNS traffic outside VPN tunnel with given DNS resolver only on UDP and DNS port
+# We want to allow DNS request from docker network
+iptables -A OUTPUT -o eth0 -p tcp --dport 53 -j ACCEPT
+iptables -A OUTPUT -o eth0 -p udp --dport 53 -j ACCEPT
+iptables -A INPUT -i eth0 -p tcp --sport 53 -j ACCEPT
+iptables -A INPUT -i eth0 -p udp --sport 53 -j ACCEPT
 
-# NOTE: these rules are dropped before starting qbittorrent
-iptables -A OUTPUT -p udp -d "${DNS_SERVER}" --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
-iptables -A INPUT -p udp -s "${DNS_SERVER}" --sport 53 -m state --state ESTABLISHED -j ACCEPT
-iptables -A OUTPUT -p tcp -d "${DNS_SERVER}" --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
-iptables -A INPUT -p tcp -s "${DNS_SERVER}" --sport 53 -m state --state ESTABLISHED -j ACCEPT
+# Allow VPN connection on eth0
+iptables -A OUTPUT -o eth0 -d ${OPENVPN_SERVER_IP} -p ${OPENVPN_SERVER_PROTO} --dport ${OPENVPN_SERVER_PORT} -j ACCEPT
+iptables -A INPUT  -i eth0 -s ${OPENVPN_SERVER_IP} -p ${OPENVPN_SERVER_PROTO} --sport ${OPENVPN_SERVER_PORT} -j ACCEPT
 
-# allow LAN traffic
-iptables -A INPUT --src "${LAN}" -j ACCEPT -i eth+
-iptables -A OUTPUT -d "${LAN}" -j ACCEPT -o eth+
+# Allow ALL on tun0
+iptables -A OUTPUT -o tun0 -d 0.0.0.0/0 -j ACCEPT
+iptables -A INPUT  -i tun0 -s 0.0.0.0/0 -j ACCEPT
 
 # allow traffic with other containers on docker network
-iptables -A INPUT --src "${DOCKER_CIDR}" -j ACCEPT -i eth+
-iptables -A OUTPUT -d "${DOCKER_CIDR}" -j ACCEPT -o eth+
-
-# allow traffic with VPN host over VPN's port and with VPN's protocol
-echo "${VPN_HOSTS_AND_PORTS}" | while IFS= read -r line; do
-VPN_HOST=$(echo "${line}" | awk '{ print $1 }')
-VPN_PORT=$(echo "${line}" | awk '{ print $2 }')
-iptables -A OUTPUT -j ACCEPT -d "${VPN_HOST}" -o eth+ -p "${VPN_PROTO}" -m "${VPN_PROTO}" --dport "${VPN_PORT}"
-iptables -A INPUT -j ACCEPT -s "${VPN_HOST}" -i eth+ -p "${VPN_PROTO}" -m "${VPN_PROTO}" --sport "${VPN_PORT}"
-done
-
-# allow traffic through VPN tunnel interface
-iptables -A INPUT -j ACCEPT -i tun+
-iptables -A OUTPUT -j ACCEPT -o tun+
+iptables -A INPUT --src "${DOCKER_CIDR}" -j ACCEPT -i eth0
+iptables -A OUTPUT -d "${DOCKER_CIDR}" -j ACCEPT -o eth0
